server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  output:
    ansi:
      enabled: always

logging:
  level:
    '[com.example.kakao]': DEBUG
    '[org.hibernate.type]': TRACE

file:
  path: ./images/
